sheetName : 2022-11-25 - LinkedIn Contacts
sheetNumber : 1
apiKey : 
apiSecret : 
startRange : 17395
endRange : 17864
authJson : 
linkedinColumn : K
emailColumn : N
nameColumn : I
titleColumn : H
categoryColumn : B
